name: build-latest
on:
  push:
    branches:
      - main

jobs:
  build-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # docker login is needed for pushing the test image
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: printenv | sort
    - run: echo "${{ github.repository }}"
    - run: docker build -t ${{ github.repository }}/${{ github.ref_name }} .
    - run: docker tag ${{ github.repository }}/${{ github.ref_name }} ${{ github.repository }}:latest
    - run: docker push ${{ github.repository }}/${{ github.ref_name }}
    - run: docker push ${{ github.repository }}:latest